### ISSUE TITLE
Preserving space

### ISSUE THREAD

**Issue by wenq1** [coderaiser/putout#129]
I have a replacer like this:

```js
                let     js_source       = `testFunc (a, b);`;

                let     replacer3   = {
                        report:         () => 'nil',
                        replace:        () => ({
                                'testFunc (__args)':          ({__args}, path1) => {
                                        __args.splice (0, 0, __args[1]);   
                                        return path1;
                                },
                        }),
                };

                let     js_output3      =  putout (js_source, {
                        plugins: [
                                ['replacer3', replacer3],
                        ],
                });
```

The output becomes, `testFunc(b, a, b)`, instead of `testFunc (b, a, b)` which preserves the original spacing. Can space preservation be achieved? For now I just use a linter as a post-step, which I don't think should be necessary.

Further to the question, if `js_source` is set to `testFunc (/** @type a */ (a), b);`, the output becomes `testFunc/** @type a */(b, a, b);`, which adds up to the spacing issue.

Very nice library indeed!

**Comment by coderaiser** [comment]
The thing is 🐊**Putout** is code transformer and it do AST-transformation mostly, for formatting you can use ESLint, or prettier, they are best in this feild.

To achive the best possible results I suggest you to use [`eslint-plugin-putout`](https://github.com/coderaiser/putout/tree/master/packages/eslint-plugin-putout#safe-mode), you can add your config on top of it, and set whitespaces count with help of [`indent`](https://eslint.org/docs/latest/rules/indent) rule.

**Comment by wenq1** [comment]
Thanks. I’m using custom plugins, and traverse the Filesystem manually, so eslint can only be used as a post step.

Regarding the second case, the output becomes testFunc/** @type a */(b, a, b);, which looks to me like a bug? As it messes up with the Jsdoc types fed into typescript.

**Comment by coderaiser** [comment]
> Regarding the second case, the output becomes testFunc/** @type a */(b, a, b);, which looks to me like a bug? As it messes up with the Jsdoc types fed into typescript.

As I see `testFunc (/** @type a */ (a), b);` transformed to `testFunc(/** @type a */ a, b);` this is the same result you will have using [no-extra-parens](https://eslint.org/docs/latest/rules/no-extra-parens) of ESLint.

**Comment by wenq1** [comment]
spacing issue is fixable. Let's take a look again at /** @type */ issue. I provide a screenshot below:

Case1:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/110781/218289928-e7a697bd-e621-4c37-9d0d-a19c66db88f2.png">

Result:
```
[2023/02/12 10:40:45.433] - js_source: testFunc (/** @type {string} */ a, b);
[2023/02/12 10:40:45.435] - js_output3.code: testFunc(b, /** @type {string} */ a, b);
```

Case2:
<img width="741" alt="image" src="https://user-images.githubusercontent.com/110781/218289946-6aec63c8-3405-4bbe-ad89-84872c1299e4.png">

Result:
```
[2023/02/12 10:42:10.574] - js_source: testFunc (/** @type {string} */ (a), b);
[2023/02/12 10:42:10.574] - js_output3.code: testFunc/** @type {string} */(b, a, b);
```

We are talking about case 2 here. Look at `/** @type {string} */` here. It is **before** the parenthesis, not **inside**, which is completely wrong.

**Comment by coderaiser** [comment]
This is related mostly to Babel and Recast, 🐊**Putout** build on top of them, so you better write to that repositories about such issues with comments.

**Comment by wenq1** [comment]
Better mention that in the docs.

**Comment by coderaiser** [comment]
Look comments is usually a bad practice, they should be made in rare cases when you need to clarify why bad code written. Why don't you just use TypeScript if you need types?

**Comment by coderaiser** [comment]
OK, we have 3 variants:
- ❌[`jscodeshift`](https://astexplorer.net/#/gist/79f2d0ef7de4aeb1a913a862217da9ec/9a2e487ad7159d9777bab7dac6d13990d94fc98c);
- ❌ [`jscodeshift + babel`](https://astexplorer.net/#/gist/04082536344ed6c41350db94b2c74747/87648709f2d75b40bc55bad06e5b2f44ae232600);
- ✅ [`babel`](https://astexplorer.net/#/gist/04082536344ed6c41350db94b2c74747/fe0bf2eaead276be190cc20af6e1d561df181e58)

So the problem in [`recast`](https://github.com/benjamn/recast). Do you have ideas for a PR?

**Comment by coderaiser** [comment]
Landed support of `CallExpression` to [`@putout/recast v1.12.0`](https://github.com/putoutjs/recast/releases/tag/v1.12.0).

Please re-install 🐊**Putout**. You can [support project](https://ko-fi.com/coderaiser.) if it helpful to you :).

**Comment by wenq1** [comment]
Regarding the recast issue, I briefly took a look.

The "leading comment" should be for argument1, not for the callee in the `CallExpression`.

**Comment by coderaiser** [comment]
Is fixed version works for you?

**Comment by wenq1** [comment]
is a new version published?

**Comment by coderaiser** [comment]
2.16.0 is version of what?

> Landed support of CallExpression to [@putout/recast v1.12.0](https://github.com/putoutjs/recast/releases/tag/v1.12.0).

> Please re-install 🐊Putout. You can [support project](https://ko-fi.com/coderaiser.) if it helpful to you :).

**Comment by wenq1** [comment]
yes it now resolves the commentary issue.

**Comment by wenq1** [comment]
However, the output is still wrong.

Input:
`testFunc (/** @type {string} */ (a), b);`

Should be transformed into
`testFunc(b, /** @type {string} */ (a), b);`

not
`testFunc(b, /** @type {string} */ a, b);`

This is the the way to do casting with JSDoc to allow tsc to work with JS files.

**Comment by coderaiser** [comment]
There is no way to keep `(` and `)`.

**Comment by wenq1** [comment]
Have you considered allowing an option to use Prettier with putout? I just came across it and reading its docs. It seems to be a better fork of benjamin's recast's printer.

**Comment by wenq1** [comment]
I have experimented with recast the whole afternoon.You are correct. There's a zillion way the output formatting went horribly wrong.

**Comment by coderaiser** [comment]
> I have experimented with recast the whole afternoon.You are correct. There's a zillion way the output formatting went horribly wrong. (e.g. https://github.com/benjamn/recast/issues/297 is really getting me mad...)

You have a couple options to not be mad:
1. Create a better tool, why not? If it will support everything Recast supports, and will have the same API I'll switch :).
2. Try to understand Recast codebase, thing that guys doing really-really-really hard (and not really interesting to spend years on).
3. Try to understand how comments presented in AST, if we talk about Babel, you have some kind of `leadingComments` and `trailingComments` as node properties, but if we talk about `ESTree`, the only thing we have is an array `comments` on top of AST:
![image](https://user-images.githubusercontent.com/1573141/218476847-1ea890d5-a581-40a1-b04c-e01d0f44d605.png)

And try to understand is it `leadingComments` or `trailingComments`? Do you have any ideas of algorithm to determine this? Is it a lot of fun to think about it?

Recast supports both, and this is some kind of magic, that we can automatically transform codebase and keep it in "our style", if our style is more or less looks similar to others code, and simple enough to be determined programmatically.

**Comment by coderaiser** [comment]
> I have experimented with recast the whole afternoon.You are correct. There's a zillion way the output formatting went horribly wrong. (e.g. https://github.com/benjamn/recast/issues/297 is really getting me mad...)

You have a couple options to not be mad:
1. Create a better tool, why not? If it will support everything Recast supports, and will have the same API I'll switch :).
2. Try to understand Recast codebase, thing that guys doing really-really-really hard (and not really interesting to spend years on).
3. Try to understand how comments presented in AST, if we talk about Babel, you have some kind of `leadingComments` and `trailingComments` as node properties, but if we talk about `ESTree`, the only thing we have is an array `comments` on top of AST:
![image](https://user-images.githubusercontent.com/1573141/218476847-1ea890d5-a581-40a1-b04c-e01d0f44d605.png)

And try to understand is it `leadingComments` or `trailingComments`? Do you have any ideas of algorithm to determine this? Is it a lot of fun to think about it?

Recast supports both, and this is some kind of magic, that we can automatically transform codebase and keep it in "our style", if our style is more or less looks similar to others code, and simple enough to be determined programmatically.

**Comment by wenq1** [comment]
Doesn't seem to be a very complex problem.

I custom-printed the ast before and after the transformation for the simple case,
`testFunc (/** @type {string} */ (a), b);`, for unshifting in an argument to the function.

Before:
```js
            {
                "type": "ExpressionStatement",
                "expression": {
                    "type": "CallExpression",
                    "callee": {
                        "type": "Identifier",
                        "name": "testFunc",
                        "loc": "f4536a95db9f707166569d7484d5ef94d3f5c1f4"
                    },
                    "arguments": [
                        {
                            "type": "Identifier",
                            "name": "a",
                            "loc": "1d878ed647d27061da8cff1399071e77c2b723b2",
                            "comments": [
                                {
                                    "type": "Block",
                                    "value": "* @type {string} ",
                                    "loc": "0ca6f7963781ef54cc9fec2192fc57d4680f6331",
                                    "leading": true,
                                    "trailing": false
                                }
                            ]
                        },
                        {
                            "type": "Identifier",
                            "name": "b",
                            "loc": "27822ab4e359a8fc41d163545e2a396cab90e8cd"
                        }
                    ],
                    "loc": "e38117ef5ea4069ab466ca36f917ff7a882ab4a8"
                },
                "loc": "7b281a851f0ad5597f9563660f9b81591fae011b"
            }
```

After:
```
            {
                "type": "ExpressionStatement",
                "expression": {
                    "type": "CallExpression",
                    "callee": {
                        "type": "Identifier",
                        "name": "testFunc",
                        "loc": "f4536a95db9f707166569d7484d5ef94d3f5c1f4"
                    },
                    "arguments": [
                        {
                            "type": "Identifier",
                            "name": "b",
                            "loc": "27822ab4e359a8fc41d163545e2a396cab90e8cd"
                        },
                        {
                            "type": "Identifier",
                            "name": "a",
                            "loc": "1d878ed647d27061da8cff1399071e77c2b723b2",
                            "comments": [
                                {
                                    "type": "Block",
                                    "value": "* @type {string} ",
                                    "loc": "0ca6f7963781ef54cc9fec2192fc57d4680f6331",
                                    "leading": true,
                                    "trailing": false
                                }
                            ]
                        },
                        {
                            "type": "Identifier",
                            "name": "b",
                            "loc": "27822ab4e359a8fc41d163545e2a396cab90e8cd"
                        }
                    ],
                    "loc": "e38117ef5ea4069ab466ca36f917ff7a882ab4a8"
                },
                "loc": "7b281a851f0ad5597f9563660f9b81591fae011b"
            }
        ],
```

Note that I did an object-hash (npm pkg of the same name) of the "loc" parameter, so that each object will sort of have a unique identifier. Now the problem just come down to making a proper diff. A quick just-diff (npm pkg of the same name) will show below:

```
diff_ops:  [
  {
    op: 'remove',
    path: [ 'program', 'body', 0, 'expression', 'arguments', 0, 'comments' ]
  },
  {
    op: 'replace',
    path: [ 'program', 'body', 0, 'expression', 'arguments', 0, 'name' ],
    value: 'b'
  },
  {
    op: 'replace',
    path: [ 'program', 'body', 0, 'expression', 'arguments', 0, 'loc' ],
    value: '27822ab4e359a8fc41d163545e2a396cab90e8cd'
  },
  {
    op: 'replace',
    path: [ 'program', 'body', 0, 'expression', 'arguments', 1, 'name' ],
    value: 'a'
  },
  {
    op: 'replace',
    path: [ 'program', 'body', 0, 'expression', 'arguments', 1, 'loc' ],
    value: '1d878ed647d27061da8cff1399071e77c2b723b2'
  },
  {
    op: 'add',
    path: [ 'program', 'body', 0, 'expression', 'arguments', 1, 'comments' ],
    value: [ [Object] ]
  },
  {
    op: 'add',
    path: [ 'program', 'body', 0, 'expression', 'arguments', 2 ],
    value: {
      type: 'Identifier',
      name: 'b',
      loc: '27822ab4e359a8fc41d163545e2a396cab90e8cd'
    }
  },
  { op: 'add', path: [ 'program', 'directives' ], value: [] },
  { op: 'add', path: [ 'program', 'interpreter' ], value: null }
]

```

Apparently diffing (RFC6902 style above) will be challenge, as the diffing algorithm is not smart enough to detect that a nested object is just inserted.

Now the problem just boils down too helping the diff to do its job properly, which can be achieved below:
- assign a proper id to the AST nodes, expose that as an api or allow for custom id generation overwrite
- mark inserted argument with a new ID
- do again the above pretty printing, this time compact the display of the nested object using ID to help with the diff
- find a better differ to diff properly

An example compacted ast dump for better diffing is as below:
```
        "body": [
            {
                "type": "ExpressionStatement",
                "expression": {
                    "type": "CallExpression",
                    "callee": {
                        "type": "Identifier",
                        "name": "testFunc",
                        "loc": "f4536a95db9f707166569d7484d5ef94d3f5c1f4"
                    },
                    "arguments": [
                        "Identifier[1d878ed647d27061da8cff1399071e77c2b723b2]",
                        "Identifier[27822ab4e359a8fc41d163545e2a396cab90e8cd]"
                    ],
                    "loc": "e38117ef5ea4069ab466ca36f917ff7a882ab4a8"
                },
                "loc": "7b281a851f0ad5597f9563660f9b81591fae011b"
            }
        ],
```

After: 
```
        "body": [
            {
                "type": "ExpressionStatement",
                "expression": {
                    "type": "CallExpression",
                    "callee": {
                        "type": "Identifier",
                        "name": "testFunc",
                        "loc": "f4536a95db9f707166569d7484d5ef94d3f5c1f4"
                    },
                    "arguments": [
                        "Identifier[<newly_inserted>]",
                        "Identifier[1d878ed647d27061da8cff1399071e77c2b723b2]",
                        "Identifier[27822ab4e359a8fc41d163545e2a396cab90e8cd]"
                    ],
                    "loc": "e38117ef5ea4069ab466ca36f917ff7a882ab4a8"
                },
                "loc": "7b281a851f0ad5597f9563660f9b81591fae011b"
            }
        ],
```

Now after a better diff is used, we could just rely the diff output ops make modifications as necessary, leaving all the unmodified nodes untouched rather than doing a pretty-print on the parent node.

Yet again, not at all complicated and need to make it appear so.
